# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5beb30d202a0b78f6cf0ad0b6aedccc60582199af5bb78026c83c3451005338b63e642a7b9c5a94bd1b426d66b21033c00b81e82416c17885c59fcddc4b2190d

test:
  secret_key_base: 1d4d9ef8157e4e24e76012182c8b97d6d9dfef13dba8b0f7c7ac080a62d943360998d637aa2e26699f90286abf8bcd4d1be2fafaa978b632a13b01356d48c942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
